# Parts of this file are adapted from https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/templates/prometheus/rules-1.14/node-exporter.yaml, distributed under Apache 2.0 Licence. That licence is at the root of this reposistry.
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: ondat
spec:
  groups:
  - name: ondat
    rules:
    - alert: VolumeReadOnly
      annotations:
        description: Filesystem of volume '{{ $labels.pvc }}/{{ $labels.pvc_namespace }}'
          has become readonly. Re-mount to restore write access.
        summary: Filesystem has become readonly.
      expr: ondat_filesystem_readonly{job="storageos-metrics-exporter-svc"} == 1
      labels:
        severity: critical
    - alert: VolumeDeviceError
      annotations:
        description: Metrics collector has reported an error collecting data from volume
          '{{ $labels.pvc }}/{{ $labels.pvc_namespace }}'. It was using statfs().
        summary: Volume filesystem collector encountered problem.
      expr: ondat_filesystem_device_error{job="storageos-metrics-exporter-svc"} == 1
      for: 1m
      labels:
        severity: warning
    - alert: VolumeFilesystemSpaceFillingUp
      annotations:
        description: Filesystem on volume '{{ $labels.pvc_namespace}}/{{ $labels.pvc }}'
          only has {{ printf "%.2f" $value }}% available space left and is filling
          up.
        summary: Filesystem is predicted to run out of space within the next 24 hours.
      expr: |-
        (
          ondat_filesystem_avail_bytes{job="storageos-metrics-exporter-svc",fstype!=""} / ondat_filesystem_size_bytes{job="storageos-metrics-exporter-svc",fstype!=""} * 100 < 15
        and
          predict_linear(ondat_filesystem_avail_bytes{job="storageos-metrics-exporter-svc",fstype!=""}[6h], 24*60*60) < 0
        and
          ondat_filesystem_readonly{job="storageos-metrics-exporter-svc",fstype!=""} == 0
        )
      for: 30m
      labels:
        severity: warning
    - alert: VolumeFilesystemSpaceFillingUp
      annotations:
        description: Filesystem on volume '{{ $labels.pvc_namespace}}/{{ $labels.pvc }}'
          only has {{ printf "%.2f" $value }}% available space left and is filling
          up fast.
        summary: Filesystem is predicted to run out of space within the next 4 hours.
      expr: |-
        (
          ondat_filesystem_avail_bytes{job="storageos-metrics-exporter-svc",fstype!=""} / ondat_filesystem_size_bytes{job="storageos-metrics-exporter-svc",fstype!=""} * 100 < 10
        and
          predict_linear(ondat_filesystem_avail_bytes{job="storageos-metrics-exporter-svc",fstype!=""}[6h], 4*60*60) < 0
        and
          ondat_filesystem_readonly{job="storageos-metrics-exporter-svc",fstype!=""} == 0
        )
      for: 15m
      labels:
        severity: critical
    - alert: VolumeFilesystemAlmostOutOfSpace
      annotations:
        description: Filesystem on volume '{{ $labels.pvc_namespace}}/{{ $labels.pvc }}'
          only has {{ printf "%.2f" $value }}% available space left.
        summary: Filesystem has less than 5% space left.
      expr: |-
        (
          ondat_filesystem_avail_bytes{job="storageos-metrics-exporter-svc",fstype!=""} / ondat_filesystem_size_bytes{job="storageos-metrics-exporter-svc",fstype!=""} * 100 < 5
        and
          ondat_filesystem_readonly{job="storageos-metrics-exporter-svc",fstype!=""} == 0
        )
      for: 15m
      labels:
        severity: warning
    - alert: VolumeFilesystemAlmostOutOfSpace
      annotations:
        description: Filesystem on volume '{{ $labels.pvc_namespace}}/{{ $labels.pvc }}'
          only has {{ printf "%.2f" $value }}% available space left.
        summary: Filesystem has less than 1% space left.
      expr: |-
        (
          ondat_filesystem_avail_bytes{job="storageos-metrics-exporter-svc",fstype!=""} / ondat_filesystem_size_bytes{job="storageos-metrics-exporter-svc",fstype!=""} * 100 < 1
        and
          ondat_filesystem_readonly{job="storageos-metrics-exporter-svc",fstype!=""} == 0
        )
      for: 1m
      labels:
        severity: critical
    - alert: VolumeFilesystemFilesFillingUp
      annotations:
        description: Filesystem on volume '{{ $labels.pvc_namespace}}/{{ $labels.pvc }}'
          only has {{ printf "%.2f" $value }}% available inodes left and is filling
          up.
        summary: Filesystem is predicted to run out of inodes within the next 24 hours.
      expr: |-
        (
          ondat_filesystem_files_free{job="storageos-metrics-exporter-svc",fstype!=""} / ondat_filesystem_files{job="storageos-metrics-exporter-svc",fstype!=""} * 100 < 40
        and
          predict_linear(ondat_filesystem_files_free{job="storageos-metrics-exporter-svc",fstype!=""}[6h], 24*60*60) < 0
        and
          ondat_filesystem_readonly{job="storageos-metrics-exporter-svc",fstype!=""} == 0
        )
      for: 30m
      labels:
        severity: warning
    - alert: VolumeFilesystemFilesFillingUp
      annotations:
        description: Filesystem on volume '{{ $labels.pvc_namespace}}/{{ $labels.pvc }}'
          only has {{ printf "%.2f" $value }}% available inodes left and is filling
          up fast.
        summary: Filesystem is predicted to run out of inodes within the next 4 hours.
      expr: |-
        (
          ondat_filesystem_files_free{job="storageos-metrics-exporter-svc",fstype!=""} / ondat_filesystem_files{job="storageos-metrics-exporter-svc",fstype!=""} * 100 < 20
        and
          predict_linear(ondat_filesystem_files_free{job="storageos-metrics-exporter-svc",fstype!=""}[6h], 4*60*60) < 0
        and
          ondat_filesystem_readonly{job="storageos-metrics-exporter-svc",fstype!=""} == 0
        )
      for: 15m
      labels:
        severity: critical
    - alert: VolumeFilesystemAlmostOutOfFiles
      annotations:
        description: Filesystem on volume '{{ $labels.pvc_namespace}}/{{ $labels.pvc }}'
          only has {{ printf "%.2f" $value }}% available inodes left.
        summary: Filesystem has less than 5% inodes left.
      expr: |-
        (
          ondat_filesystem_files_free{job="storageos-metrics-exporter-svc",fstype!=""} / ondat_filesystem_files{job="storageos-metrics-exporter-svc",fstype!=""} * 100 < 5
        and
          ondat_filesystem_readonly{job="storageos-metrics-exporter-svc",fstype!=""} == 0
        )
      for: 15m
      labels:
        severity: warning
    - alert: VolumeFilesystemAlmostOutOfFiles
      annotations:
        description: Filesystem on volume '{{ $labels.pvc_namespace}}/{{ $labels.pvc }}'
          only has {{ printf "%.2f" $value }}% available inodes left.
        summary: Filesystem has less than 3% inodes left.
      expr: |-
        (
          ondat_filesystem_files_free{job="storageos-metrics-exporter-svc",fstype!=""} / ondat_filesystem_files{job="storageos-metrics-exporter-svc",fstype!=""} * 100 < 3
        and
          ondat_filesystem_readonly{job="storageos-metrics-exporter-svc",fstype!=""} == 0
        )
      for: 1m
      labels:
        severity: critical
