# configure golangci-lint
# see https://github.com/golangci/golangci-lint/blob/master/.golangci.example.yml for examples
# see https://golangci-lint.run/usage/linters for list of linters
linters:
  enable:
    - nilerr
    - whitespace
    - gofmt
    - misspell
    - forbidigo
    - asciicheck

issues:
  exclude-rules:
    - path: _test\.go
      linters:
      - dupl
      - goconst

linters-settings:
  govet:
    # Report about shadowed variables
    check-shadowing: false
  gosimple:
    go: "1.17"
    checks: [ "-S1019" ]
  forbidigo:
    forbid:
      - ^print.*(# Do not commit print statements)?
      - ^fmt\.Print.*(# Do not commit print statements)?
