//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricsExporterConfig) DeepCopyInto(out *MetricsExporterConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.MetricsExporterConfigSpec.DeepCopyInto(&out.MetricsExporterConfigSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricsExporterConfig.
func (in *MetricsExporterConfig) DeepCopy() *MetricsExporterConfig {
	if in == nil {
		return nil
	}
	out := new(MetricsExporterConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MetricsExporterConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricsExporterConfigSpec) DeepCopyInto(out *MetricsExporterConfigSpec) {
	*out = *in
	if in.DisabledCollectors != nil {
		in, out := &in.DisabledCollectors, &out.DisabledCollectors
		*out = make([]MetricsExporterCollector, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricsExporterConfigSpec.
func (in *MetricsExporterConfigSpec) DeepCopy() *MetricsExporterConfigSpec {
	if in == nil {
		return nil
	}
	out := new(MetricsExporterConfigSpec)
	in.DeepCopyInto(out)
	return out
}
