apiVersion: v1
kind: Service
metadata:
  labels:
    app: storageos
    service-discovery: storageos-metrics-exporter
  name: storageos-metrics-exporter-svc
  namespace: storageos
spec:
  clusterIP: None
  ports:
  - name: metrics
    port: 9100
  selector:
    app: storageos
    category: metrics-exporter
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: storageos
  name: storageos-metrics-exporter
  namespace: storageos
spec:
  selector:
    matchLabels:
      app: storageos
  template:
    metadata:
      labels:
        app: storageos
        category: metrics-exporter
    spec:
      containers:
      - image: storageos/metrics-exporter:v0.1.2
        imagePullPolicy: IfNotPresent
        name: storageos-metrics-exporter
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /var/lib/storageos
          name: state
          readOnly: true
        - mountPath: /var/lib/kubelet
          mountPropagation: Bidirectional
          name: kubelet-dir
          readOnly: true
        - mountPath: /etc/storageos/secrets/api
          name: api-secret
          readOnly: true
      volumes:
      - hostPath:
          path: /var/lib/storageos
        name: state
      - hostPath:
          path: /var/lib/kubelet
          type: Directory
        name: kubelet-dir
      - name: api-secret
        secret:
          secretName: storageos-api
