apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: storageos
    app.kubernetes.io/component: metrics-exporter
  name: storageos-metrics-exporter
  namespace: storageos
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: storageos
    app.kubernetes.io/component: metrics-exporter
  name: storageos:metrics-exporter
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - privileged
  resources:
  - securitycontextconstraints
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: storageos
    app.kubernetes.io/component: metrics-exporter
  name: storageos:metrics-exporter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: storageos:metrics-exporter
subjects:
- kind: ServiceAccount
  name: storageos-metrics-exporter
  namespace: storageos
---
apiVersion: v1
data:
  config.yaml: |
    apiVersion: config.storageos.com/v1
    kind: MetricsExporterConfig
    logLevel: info
    timeout: 10
kind: ConfigMap
metadata:
  labels:
    app: storageos
    app.kubernetes.io/component: metrics-exporter
  name: storageos-metrics-exporter
  namespace: storageos
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: storageos
    app.kubernetes.io/component: metrics-exporter
  name: storageos-metrics-exporter
  namespace: storageos
spec:
  clusterIP: None
  ports:
  - name: metrics
    port: 9100
  selector:
    app: storageos
    app.kubernetes.io/component: metrics-exporter
    category: metrics-exporter
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: storageos
    app.kubernetes.io/component: metrics-exporter
  name: storageos-metrics-exporter
  namespace: storageos
spec:
  selector:
    matchLabels:
      app: storageos
      app.kubernetes.io/component: metrics-exporter
  template:
    metadata:
      labels:
        app: storageos
        app.kubernetes.io/component: metrics-exporter
        category: metrics-exporter
    spec:
      containers:
      - args:
        - -config
        - /etc/storageos/metrics-exporter-config.yaml
        image: storageos/metrics-exporter:v0.1.7
        imagePullPolicy: IfNotPresent
        name: storageos-metrics-exporter
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /var/lib/storageos
          mountPropagation: HostToContainer
          name: state
          readOnly: true
        - mountPath: /var/lib/kubelet
          mountPropagation: HostToContainer
          name: kubelet-dir
          readOnly: true
        - mountPath: /etc/storageos/metrics-exporter-config.yaml
          name: storageos-metrics-exporter
          readOnly: true
          subPath: config.yaml
      serviceAccountName: storageos-metrics-exporter
      volumes:
      - hostPath:
          path: /var/lib/storageos
        name: state
      - hostPath:
          path: /var/lib/kubelet
          type: Directory
        name: kubelet-dir
      - configMap:
          name: storageos-metrics-exporter
        name: storageos-metrics-exporter
