---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: storageos-metrics-exporter
spec:
  selector:
    matchLabels:
      app: storageos
  template:
    metadata:
      labels:
        app: storageos
        category: metrics-exporter
    spec:
      serviceAccountName: storageos-metrics-exporter
      containers:
        - name: storageos-metrics-exporter
          args: ["-config", "/etc/storageos/metrics-exporter-config.yaml"]
          image: storageos/metrics-exporter:v0.1.7
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /var/lib/storageos
              name: state
              readOnly: true
              mountPropagation: HostToContainer
            - mountPath: /var/lib/kubelet
              name: kubelet-dir
              readOnly: true
              mountPropagation: HostToContainer
            - mountPath: /etc/storageos/metrics-exporter-config.yaml
              name: storageos-metrics-exporter
              readOnly: true
              subPath: config.yaml
          securityContext:
            privileged: true
      volumes:
        - hostPath:
            path: /var/lib/storageos
          name: state
        - hostPath:
            path: /var/lib/kubelet
            type: Directory
          name: kubelet-dir
        - name: storageos-metrics-exporter
          configMap:
            name: storageos-metrics-exporter
