namespace: storageos

commonLabels:
  app: storageos

resources:
- rbac.yaml
- daemonset.yaml
- service.yaml

configMapGenerator:
  - name: storageos-metrics-exporter
    files:
      - metrics-exporter-config.yaml
