namespace: storageos

commonLabels:
  app: storageos
  app.kubernetes.io/component: metrics-exporter

resources:
- rbac.yaml
- daemonset.yaml
- service.yaml

configMapGenerator:
  - name: storageos-metrics-exporter
    files:
      - metrics-exporter-config.yaml

generatorOptions:
  disableNameSuffixHash: true
