apiVersion: v1
kind: Service
metadata:
  name: storageos-metrics-exporter
  labels:
    service-discovery: storageos-metrics-exporter
spec:
  selector:
    category: metrics-exporter
  ports:
  - name: metrics
    port: 9100
  clusterIP: "None" # headless
