{
 "title": "Ondat / Volume",
 "description": "K8s persistent volume usage",
 "tags": [
  "ondat",
  "kubernetes"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(ondat_disk_info{job=\"storageos-metrics-exporter-svc\"}, pvc_namespace)"
    }
   },
   {
    "name": "volume",
    "label": "PersistentVolumeClaim",
    "query": {
     "query": "label_values(ondat_disk_info{pvc_namespace=\"$namespace\", job=\"storageos-metrics-exporter-svc\"}, pvc)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Current I/Os",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 21, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "ondat_disk_io_now{job=\"storageos-metrics-exporter-svc\", pvc_namespace=\"$namespace\", pvc=\"$volume\"}",
     "legendFormat": "Current I/Os"
    }
   ]
  },
  {
   "title": "Read-only status",
   "type": "stat",
   "gridPos": { "h": 10, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max without(pod, device, mountpoint, instance) (ondat_filesystem_readonly{job=\"storageos-metrics-exporter-svc\", pvc_namespace=\"$namespace\", pvc=\"$volume\"})"
    }
   ]
  },
  {
   "title": "Reads & Writes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 21, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "irate(ondat_disk_written_bytes_total{job=\"storageos-metrics-exporter-svc\", pvc_namespace=\"$namespace\", pvc=\"$volume\"}[5m])",
     "legendFormat": "Writes"
    },
    {
     "expr": "irate(ondat_disk_read_bytes_total{job=\"storageos-metrics-exporter-svc\", pvc_namespace=\"$namespace\", pvc=\"$volume\"}[5m])",
     "legendFormat": "Reads"
    }
   ]
  },
  {
   "title": "Device error status",
   "type": "stat",
   "gridPos": { "h": 10, "w": 3, "x": 21, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max without(pod, device, mountpoint, instance) (ondat_filesystem_device_error{job=\"storageos-metrics-exporter-svc\", pvc_namespace=\"$namespace\", pvc=\"$volume\"})"
    }
   ]
  },
  {
   "title": "Volume Space Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(\n  sum (ondat_filesystem_size_bytes{job=\"storageos-metrics-exporter-svc\", pvc_namespace=\"$namespace\", pvc=\"$volume\"})\n  -\n  sum (ondat_filesystem_avail_bytes{job=\"storageos-metrics-exporter-svc\", pvc_namespace=\"$namespace\", pvc=\"$volume\"})\n)",
     "legendFormat": "Used Space"
    },
    {
     "expr": "sum (ondat_filesystem_avail_bytes{job=\"storageos-metrics-exporter-svc\", pvc_namespace=\"$namespace\", pvc=\"$volume\"})",
     "legendFormat": "Free Space"
    }
   ]
  },
  {
   "title": "Volume Space Usage",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max without(pod, device, mountpoint, instance) (\n(\n  (topk(1, ondat_filesystem_size_bytes{job=\"storageos-metrics-exporter-svc\", pvc_namespace=\"$namespace\", pvc=\"$volume\"}))\n  -\n  (topk(1, ondat_filesystem_avail_bytes{job=\"storageos-metrics-exporter-svc\", pvc_namespace=\"$namespace\", pvc=\"$volume\"}))\n)\n/\ntopk(1, ondat_filesystem_size_bytes{job=\"storageos-metrics-exporter-svc\", pvc_namespace=\"$namespace\", pvc=\"$volume\"})\n* 100)"
    }
   ]
  },
  {
   "title": "Volume Inode Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(\n  sum (ondat_filesystem_files{job=\"storageos-metrics-exporter-svc\", pvc_namespace=\"$namespace\", pvc=\"$volume\"})\n  -\n  sum (ondat_filesystem_files_free{job=\"storageos-metrics-exporter-svc\", pvc_namespace=\"$namespace\", pvc=\"$volume\"})\n)",
     "legendFormat": "Inodes Used"
    },
    {
     "expr": "sum (ondat_filesystem_files_free{job=\"storageos-metrics-exporter-svc\", pvc_namespace=\"$namespace\", pvc=\"$volume\"})",
     "legendFormat": "Inodes Free"
    }
   ]
  },
  {
   "title": "Volume Inode Usage",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max without(pod, device, mountpoint, instance) (\n  (\n    (topk(1, ondat_filesystem_files{job=\"storageos-metrics-exporter-svc\", pvc_namespace=\"$namespace\", pvc=\"$volume\"}))\n    -\n    (topk(1, ondat_filesystem_files_free{job=\"storageos-metrics-exporter-svc\", pvc_namespace=\"$namespace\", pvc=\"$volume\"}))\n  )\n  /\n  topk(1, ondat_filesystem_files{job=\"storageos-metrics-exporter-svc\", pvc_namespace=\"$namespace\", pvc=\"$volume\"})\n* 100)"
    }
   ]
  }
 ]
}