apiVersion: apps/v1
kind: DaemonSet
metadata:
 name: monitor-test
 namespace: storageos
spec:
 selector:
   matchLabels:
     app: storageos
 template:
   metadata:
     labels:
       app: storageos
   spec:
     serviceAccountName: storageos-api-manager
    #  securityContext:
    #   fsGroup: 65532
     containers:
      - name: monitor-test
        image: docker.rickos.site/ricosorio/metrics-exporter:latest
        imagePullPolicy: Always
        volumeMounts:
         - mountPath: /var/lib/storageos
           name: state
         - mountPath: /var/lib/kubelet
           name: kubelet-dir
         - mountPath: /etc/storageos/secrets/api
           name: api-secret
     volumes:
     - hostPath:
         path: /var/lib/storageos
       name: state
     - hostPath:
         path: /var/lib/kubelet
         type: Directory
       name: kubelet-dir
     - name: api-secret
       secret:
        secretName: storageos-api

