apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: storageos-metrics-exporter
  namespace: storageos
spec:
 selector:
   matchLabels:
     app: storageos
 template:
   metadata:
     labels:
        app: storageos
        category: metrics-exporter
   spec:
     serviceAccountName: storageos-api-manager # add its own or use default
     containers:
      - name: storageos-metrics-exporter
        image: docker.rickos.site/ricosorio/metrics-exporter:latest # use storageos registry
        imagePullPolicy: Always # revert to default
        volumeMounts:
         - mountPath: /var/lib/storageos
           name: state
           readOnly: true
         - mountPath: /var/lib/kubelet
           name: kubelet-dir
           readOnly: true
         - mountPath: /etc/storageos/secrets/api
           name: api-secret
           readOnly: true
     volumes:
     - hostPath:
         path: /var/lib/storageos
       name: state
     - hostPath:
         path: /var/lib/kubelet
         type: Directory
       name: kubelet-dir
     - name: api-secret
       secret:
        secretName: storageos-api

