# single instance to test endpoint and metrics being gathered
# requires prometheus CRD to be installed (k create -f https://github.com/prometheus-operator/prometheus-operator/releases/download/v0.55.0/bundle.yaml)
# this would be the customers responsability
# data is not being persisted between restarts
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  labels:
    app: storageos
spec:
  serviceAccountName: prometheus-service-account
  serviceMonitorSelector: {} # all
    # matchLabels:
    #   app: storageos
  serviceMonitorNamespaceSelector: {} # all
    # matchLabels:
    #   app: storageos