name: Build and publish

on: [ push ]

jobs:
  bundle-up-to-date:  
    name: Bundle.yaml is up to date
    runs-on: ubuntu-18.04
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - name: Install kustomize
        run: curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build bundle.yaml
        run: make bundle
      - name: Check diff
        run: git diff --exit-code -- manifests/bundle.yaml
  golangci:
    name: Go Linter
    runs-on: ubuntu-18.04
    needs: bundle-up-to-date
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential
          sudo apt install -y libdevmapper-dev
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
         go-version: 1.17
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run linter
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          args: -c=".github/linters-cfg/.golangci.yml"
  superlinter:
    name: Super Linter (non-Go)
    runs-on: ubuntu-18.04
    needs: bundle-up-to-date
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0
      - name: Run linter
        uses: github/super-linter/slim@v4 # slim image has -2gb and excludes support for languages we don't use
        env:
          VALIDATE_ALL_CODEBASE: false # only new or edited files
          FILTER_REGEX_EXCLUDE: vendor/* # avoid linting deps
          VALIDATE_MARKDOWN: true
          VALIDATE_SHELL_SHFMT: true
          VALIDATE_YAML: true
          VALIDATE_BASH: true
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          IGNORE_GITIGNORED_FILES: true
          LINTER_RULES_PATH: .github/linters-cfg # markdown and yaml cfg files used
  build:
    name: Build binary
    runs-on: ubuntu-18.04
    needs: [golangci, superlinter]
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
         go-version: 1.17
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build binary
        run: make build
  publish-image:
    # if: startsWith(github.event.base_ref, 'refs/heads/release/v')
    runs-on: ubuntu-18.04
    name: Publish image
    needs: build
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.gitRef }}
      - name: Login to registry
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_CLI_USERNAME }}
          password: ${{ secrets.DOCKERHUB_CLI_PASSWORD }}

      - name: Set image env vars
        run: echo $GITHUB_BASE_REF
      - name: Set image env vars
        run: echo $GITHUB_REF
      - name: Set image env vars
        run: echo "Extract res ${GITHUB_BASE_REF#release/:-${GITHUB_REF#refs/heads/release/}}"
      - name: Set image env vars
        run: echo "VERSION=${GITHUB_BASE_REF#release/:-${GITHUB_REF#refs/heads/release/}}" >> $GITHUB_ENV
      - name: Set image env vars
        run: echo "IMAGE=metrics-exporter:${VERSION}" >> $GITHUB_ENV
      - name: Set image env vars
        run: cat $GITHUB_ENV
      - name: Set image env vars
        run: echo "base_ref ${{ github.event.base_ref }}"

      - name: Build image
        run: make docker-build
      # - name: Push image
      #   run: make docker-push