name: Check bundle.yaml is up to date

on: [ push ]

jobs:
  bundle-up-to-date:
    name: Bundle.yaml is up to date
    runs-on: ubuntu-18.04
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - name: Install kustomize
        run: curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build bundle.yaml
        run: make bundle
      - name: Check diff
        run: git diff --exit-code -- manifests/bundle.yaml