name: Publish image to dockerhub registry

# Automatically push a new docker image into the dockerhub registry
# Triggered on a push of a branch prefixed with "release/v" and tagged with "v*"

on:
  workflow_run:
    workflows: ["Build"]
    branches: ['release/v**']
    types: [completed]

jobs:
  publish-image:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-18.04
    name: Publish image
    env:
      VERSION: GITHUB_BASE_REF#release/:-${GITHUB_REF#refs/heads/release/}
      VERSION2: ${GITHUB_BASE_REF#release/:-${GITHUB_REF#refs/heads/release/}}
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.gitRef }}
      - name: Login to registry
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_CLI_USERNAME }}
          password: ${{ secrets.DOCKERHUB_CLI_PASSWORD }}
      - name: Set image env vars
        run: |
          echo "IMAGE=metrics-exporter:${VERSION}" >> $GITHUB_ENV
          echo $IMAGE
          echo $VERSION
          echo $VERSION2
          echo ${IMAGE}
          echo ${VERSION}
          echo -$VERSION2-
          echo Why don't you work
      - name: Print context
        run: echo "$GITHUB_CONTEXT"
      - name: Build image
        run: make docker-build
      # - name: Push image
      #   run: make docker-push

      # TODO img tagged 'v*' and another 'latest'?