name: Publish image to dockerhub registry

# Automatically push a new docker image into the dockerhub registry
# Triggered on a push of a branch prefixed with "release/v" and tagged with "v*"

on:
  workflow_run:
    workflows: ["Build"]
    branches: ['release/v*']
    types: 
      - completed

jobs:
  publish-image:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    #if: startsWith(github.event.base_ref, 'refs/heads/release/v')
    runs-on: ubuntu-18.04
    name: Publish image
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.gitRef }}
      - name: Login to registry
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_CLI_USERNAME }}
          password: ${{ secrets.DOCKERHUB_CLI_PASSWORD }}
      - name: Set image env vars
        # Refer to https://stackoverflow.com/a/58178121 for git tag extraction.
        run: |
          echo "VERSION=${{ github.event.inputs.imageTag }}" >> $GITHUB_ENV
          echo "IMAGE=metrics-exporter:${VERSION}" >> $GITHUB_ENV
          echo $VERSION
          echo ${{ env.VERSION }}
          echo $IMAGE
          echo ${{ env.IMAGE }}
      - name: Build image
        run: make docker-build
      # - name: Push image
      #   run: make docker-push

      # TODO img tagged 'v*' and another 'latest'?